use_frameworks!
platform :ios, '15.6'

target 'QuickTodo' do
  # core RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'

  # Community projects
  pod 'Action', '~> 4.0'
  pod 'NSObject+Rx', '~> 5.1'
  
  # Realm database
  pod 'RealmSwift', '~> 10.0'
  pod 'RxRealm', '~> 5.0'
end
