platform :ios, '15.6'

# Hue has some warnings, let's silence them.
inhibit_all_warnings!

target 'Testing' do
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Hue'

  target 'TestingTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end
end
