use_frameworks!
source 'https://cdn.cocoapods.org'
inhibit_all_warnings!

abstract_target 'TweetieAbstract' do
    pod 'Alamofire', '4.9.1'

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'RealmSwift', '10.21.0'
    pod 'RxRealm', '5.0.4'
    pod 'Unbox', '4.0.0'
    pod 'Then', '2.7.0'
    pod 'Reachability', '3.2.0'

    target 'Tweetie' do
        platform :ios, '15.6'
        pod 'RxDataSources', '5.0.0'
    end
    
    target 'MacTweetie' do
        platform :osx, '10.14'
    end
    
    target 'TweetieTests' do
        platform :ios, '15.6'
        pod 'RxTest', '6.5.0'
        pod 'RxBlocking', '6.5.0'
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end
